query {
  order(id: $orderID) {
    fulfillmentOrders(first: 64, query: "status:OPEN") {
      nodes {
        id
        status
        supportedActions {
          action
        }
        lineItems(first: 64) {
          nodes {
            id
            quantity
          }
        }
      }
    }
  }
}

